### ISSUE TITLE
How does everyone delete, clean or remove images out of S3?

### ISSUE THREAD

**Issue by squarism** [dogestry/dogestry#104]
How can I untag / delete / clean images?
I think I see how to do it manually but I was wondering how people that have been using dogestry for a while do it.

Something like this maybe?  Assume I did a `dogestry push ubuntu`.
```
# find all the layers used by ubuntu
docker history ubuntu

IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
6b4adea2c00e        7 days ago          /bin/sh -c #(nop) CMD ["/bin/bash"]             0 B
ce23f7861d68        7 days ago          /bin/sh -c sed -i 's/^#\s*\(deb.*universe\)$/   1.911 kB
2e95ee7a6bba        7 days ago          /bin/sh -c echo '#!/bin/sh' > /usr/sbin/polic   156.2 kB
5f0ca2331640        7 days ago          /bin/sh -c #(nop) ADD file:037585e370463e3c37   137.4 MB

# delete layers in the s3 bucket your-repo/images/{layer}
# psuedocode
for a in `ls your-registry/images/${image_sha}; do
  s3cmd rm $a
done

# delete repository name/tag
s3cmd rm repositories/your-tag
```

**Comment by dselans** [comment]
@squarism what you have for an existing container with *known* image id's is just about right.

The problem is a bit more difficult when it comes to images (and layers) that are no longer used.

I feel like this is functionality that dogestry could benefit from. I'll create a separate issue/feature request for delete functionality.

**Comment by relistan** [comment]
Clsing in favor of #110
